services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll   # Mount current folder into container
    stdin_open: true
    tty: true

  jekyll-build:
    build: .
    volumes:
      - .:/srv/jekyll
      - ./_site:/srv/jekyll/_site   # Output folder
    command: ["jekyll", "build"]